/*
 * generated by Xtext 2.14.0
 */
package fsm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTextEditorScopeProvider extends DelegatingScopeProvider {
}
