/**
 * generated by Xtext 2.14.0
 */
package fsm.ui;

import fsm.ui.AbstractTextEditorUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TextEditorUiModule extends AbstractTextEditorUiModule {
  public TextEditorUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
