/**
 * generated by Xtext 2.14.0
 */
package fsm;

import fsm.TextEditorStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TextEditorStandaloneSetup extends TextEditorStandaloneSetupGenerated {
  public static void doSetup() {
    new TextEditorStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
