/**
 * generated by Xtext 2.14.0
 */
package fsm;

import fsm.AbstractTextEditorRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TextEditorRuntimeModule extends AbstractTextEditorRuntimeModule {
}
