/**
 * generated by Xtext 2.14.0
 */
package fsm.ide;

import fsm.ide.AbstractTextEditorIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TextEditorIdeModule extends AbstractTextEditorIdeModule {
}
