/**
 * generated by Xtext 2.14.0
 */
package fsm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fsm.TextEditorRuntimeModule;
import fsm.TextEditorStandaloneSetup;
import fsm.ide.TextEditorIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TextEditorIdeSetup extends TextEditorStandaloneSetup {
  @Override
  public Injector createInjector() {
    TextEditorRuntimeModule _textEditorRuntimeModule = new TextEditorRuntimeModule();
    TextEditorIdeModule _textEditorIdeModule = new TextEditorIdeModule();
    return Guice.createInjector(Modules2.mixin(_textEditorRuntimeModule, _textEditorIdeModule));
  }
}
