/*
 * generated by Xtext 2.14.0
 */
package fsm.ui.tests;

import com.google.inject.Injector;
import fsm.textEditor.ui.internal.TextEditorActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TextEditorUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TextEditorActivator.getInstance().getInjector("fsm.TextEditor");
	}

}
