/**
 * generated by Xtext 2.14.0
 */
package fsm.ui.contentassist;

import fsm.ui.contentassist.AbstractTextEditorProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TextEditorProposalProvider extends AbstractTextEditorProposalProvider {
}
